spring:
  application:
    name: api-sphere
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    h2:
      console:
        enabled: true
        path: /h2-console
    sql:
      init:
        mode: always
    jpa:
      defer-datasource-initialization: true
    config:
      import: "optional:configserver:"
